#!/bin/bash

set -e

echo "Starting Minecraft NeoForge server..."
echo "Minecraft Version: ${MC_VERSION}"
echo "NeoForge Version: ${NEOFORGE_VERSION}"
echo "Memory: ${MEMORY_MIN} - ${MEMORY_MAX}"

# Handle EULA
if [ "$EULA" = "TRUE" ] || [ "$EULA" = "true" ]; then
    echo "eula=true" > eula.txt
    echo "EULA accepted via environment variable"
else
    if [ ! -f eula.txt ]; then
        echo "eula=false" > eula.txt
        echo "ERROR: You must accept the Minecraft EULA!"
        echo "Set environment variable EULA=TRUE to accept"
        echo "By setting this, you agree to https://www.minecraft.net/en-us/eula"
        exit 1
    fi
fi

# Configure server.properties if it doesn't exist
if [ ! -f server.properties ]; then
    echo "Creating default server.properties..."
    cat > server.properties <<EOF
# Minecraft server properties
# Generated by Docker container
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=easy
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
EOF
fi

# Find the correct run script
RUN_SCRIPT=""
if [ -f "run.sh" ]; then
    RUN_SCRIPT="run.sh"
elif [ -f "user_jvm_args.txt" ]; then
    # NeoForge 1.20.2+ style
    # Create a simple launcher that respects our memory settings
    echo "Creating launcher script..."
    cat > run_server.sh <<EOF
#!/bin/bash
java -Xms${MEMORY_MIN} -Xmx${MEMORY_MAX} \\
    -XX:+UseG1GC \\
    -XX:+ParallelRefProcEnabled \\
    -XX:MaxGCPauseMillis=200 \\
    -XX:+UnlockExperimentalVMOptions \\
    -XX:+DisableExplicitGC \\
    -XX:+AlwaysPreTouch \\
    -XX:G1NewSizePercent=30 \\
    -XX:G1MaxNewSizePercent=40 \\
    -XX:G1HeapRegionSize=8M \\
    -XX:G1ReservePercent=20 \\
    -XX:G1HeapWastePercent=5 \\
    -XX:G1MixedGCCountTarget=4 \\
    -XX:InitiatingHeapOccupancyPercent=15 \\
    -XX:G1MixedGCLiveThresholdPercent=90 \\
    -XX:G1RSetUpdatingPauseTimePercent=5 \\
    -XX:SurvivorRatio=32 \\
    -XX:+PerfDisableSharedMem \\
    -XX:MaxTenuringThreshold=1 \\
    -Dusing.aikars.flags=https://mcflags.emc.gs \\
    -Daikars.new.flags=true \\
    @libraries/net/neoforged/neoforge/*/unix_args.txt \\
    nogui
EOF
    chmod +x run_server.sh
    RUN_SCRIPT="run_server.sh"
fi

# Launch the server
if [ -n "$RUN_SCRIPT" ]; then
    echo "Launching server with $RUN_SCRIPT..."
    exec ./$RUN_SCRIPT
else
    echo "ERROR: Could not find server launch script!"
    exit 1
fi
